backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads" # Where uploaded images will be stored
public_folder: "/uploads"

site_url: "https://realcricket.netlify.app" # Your site URL

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Image", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "content/pages/about.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Body", widget: "markdown" }

      - name: "contact"
        label: "Contact Page"
        file: "content/pages/contact.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Body", widget: "markdown" }

publish_mode: editorial_workflow
